# Tensor equations

A reimplementation of my loved *[hTensor](http://dis.um.es/profesores/alberto/material/hTensor.pdf)* con numpy.

See also [Multilinear Algebra for Visual Geometry](http://dis.um.es/profesores/alberto/material/mvigro-td.pdf)

In [1]:
import sympy
import numpy as np
import numpy.linalg as la

from umucv.tensor import T, mul, mapAt

def sht(t):
    return Matrix(t.A.tolist())

def delta(n):
    return T(np.eye(n))

## Simple example

In [2]:
M1 = np.matrix('1 2 3; 4 5 7').A
M2 = np.matrix('2 1 1; 1 -1 5').A

In [3]:
M = T(np.array([M1,M2]),'cvw')

M

T([[[ 1,  2,  3],
    [ 4,  5,  7]],

   [[ 2,  1,  1],
    [ 1, -1,  5]]],'cvw')

In [4]:
X = T(np.array([7,0,7]),'w')

X

T([7, 0, 7],'w')

In [5]:
v = M @ X

v

T([[28, 77],
   [21, 42]],'cv')

In [6]:
v / M

 [2 2] [3] [2 2] [] (4, 3) (4, 1) 


T([7.00000000e+00, 2.66453526e-15, 7.00000000e+00],'w')

In [7]:
X = T(np.array([[7,0,7],[3,3,1]]),'nw')

X

T([[7, 0, 7],
   [3, 3, 1]],'nw')

In [8]:
v = M @ X

v

T([[[28, 77],
    [12, 34]],

   [[21, 42],
    [10,  5]]],'cnv')

In [9]:
v / M

 [2 2] [3] [2 2] [2] (4, 3) (4, 2) 


T([[7.00000000e+00, 3.00000000e+00],
   [2.66453526e-15, 3.00000000e+00],
   [7.00000000e+00, 1.00000000e+00]],'wn')

## Fundamental matrix

In [10]:
v1s = '''
 0.131250  -0.321875
-0.046875  -0.225000
-0.206250  -0.121875
-0.353125  -0.043750
 0.156250  -0.200000
-0.037500  -0.100000
-0.215625   0.006250
-0.356250   0.093750
 0.187500  -0.040625
-0.012500   0.068750
-0.215625   0.168750
-0.381250   0.250000
 0.237500   0.159375
 0.009375   0.256250
-0.218750   0.359375
-0.396875   0.446875
 0.362500   0.290625
 0.137500   0.393750
-0.062500   0.478125
-0.234375   0.550000
 0.462500   0.415625
 0.256250   0.490625
 0.056250   0.578125
-0.109375   0.628125
 0.543750   0.496875
 0.343750   0.568750
 0.146875   0.634375
 0.006250   0.684375
'''

v2s ='''
 0.425000  -0.496875
 0.293750  -0.556250
 0.134375  -0.606250
-0.056250  -0.687500
 0.465625  -0.368750
 0.325000  -0.418750
 0.146875  -0.481250
-0.034375  -0.537500
 0.515625  -0.209375
 0.365625  -0.253125
 0.181250  -0.318750
-0.012500  -0.368750
 0.568750  -0.034375
 0.403125  -0.078125
 0.212500  -0.137500
-0.003125  -0.184375
 0.418750   0.068750
 0.271875   0.040625
 0.090625  -0.000000
-0.115625  -0.046875
 0.293750   0.162500
 0.159375   0.137500
-0.021875   0.106250
-0.209375   0.062500
 0.196875   0.218750
 0.065625   0.196875
-0.100000   0.171875
-0.278125   0.143750
'''

import cv2
from io import StringIO
from umucv.htrans import homog, inhomog

v1 = T(homog(np.loadtxt(StringIO(v1s))),'ni')
v2 = T(homog(np.loadtxt(StringIO(v2s))),'nj')

In [11]:
v1

T([[ 0.13125 , -0.321875,  1.      ],
   [-0.046875, -0.225   ,  1.      ],
   [-0.20625 , -0.121875,  1.      ],
   [-0.353125, -0.04375 ,  1.      ],
   [ 0.15625 , -0.2     ,  1.      ],
   [-0.0375  , -0.1     ,  1.      ],
   [-0.215625,  0.00625 ,  1.      ],
   [-0.35625 ,  0.09375 ,  1.      ],
   [ 0.1875  , -0.040625,  1.      ],
   [-0.0125  ,  0.06875 ,  1.      ],
   [-0.215625,  0.16875 ,  1.      ],
   [-0.38125 ,  0.25    ,  1.      ],
   [ 0.2375  ,  0.159375,  1.      ],
   [ 0.009375,  0.25625 ,  1.      ],
   [-0.21875 ,  0.359375,  1.      ],
   [-0.396875,  0.446875,  1.      ],
   [ 0.3625  ,  0.290625,  1.      ],
   [ 0.1375  ,  0.39375 ,  1.      ],
   [-0.0625  ,  0.478125,  1.      ],
   [-0.234375,  0.55    ,  1.      ],
   [ 0.4625  ,  0.415625,  1.      ],
   [ 0.25625 ,  0.490625,  1.      ],
   [ 0.05625 ,  0.578125,  1.      ],
   [-0.109375,  0.628125,  1.      ],
   [ 0.54375 ,  0.496875,  1.      ],
   [ 0.34375 ,  0.56875 ,  1.      ],
   [ 0.14687

In [12]:
v2

T([[ 0.425   , -0.496875,  1.      ],
   [ 0.29375 , -0.55625 ,  1.      ],
   [ 0.134375, -0.60625 ,  1.      ],
   [-0.05625 , -0.6875  ,  1.      ],
   [ 0.465625, -0.36875 ,  1.      ],
   [ 0.325   , -0.41875 ,  1.      ],
   [ 0.146875, -0.48125 ,  1.      ],
   [-0.034375, -0.5375  ,  1.      ],
   [ 0.515625, -0.209375,  1.      ],
   [ 0.365625, -0.253125,  1.      ],
   [ 0.18125 , -0.31875 ,  1.      ],
   [-0.0125  , -0.36875 ,  1.      ],
   [ 0.56875 , -0.034375,  1.      ],
   [ 0.403125, -0.078125,  1.      ],
   [ 0.2125  , -0.1375  ,  1.      ],
   [-0.003125, -0.184375,  1.      ],
   [ 0.41875 ,  0.06875 ,  1.      ],
   [ 0.271875,  0.040625,  1.      ],
   [ 0.090625, -0.      ,  1.      ],
   [-0.115625, -0.046875,  1.      ],
   [ 0.29375 ,  0.1625  ,  1.      ],
   [ 0.159375,  0.1375  ,  1.      ],
   [-0.021875,  0.10625 ,  1.      ],
   [-0.209375,  0.0625  ,  1.      ],
   [ 0.196875,  0.21875 ,  1.      ],
   [ 0.065625,  0.196875,  1.      ],
   [-0.1    

In [13]:
D = v1 * v2

D.reorder('nij')

T([[[ 5.57812500e-02, -6.52148438e-02,  1.31250000e-01],
    [-1.36796875e-01,  1.59931641e-01, -3.21875000e-01],
    [ 4.25000000e-01, -4.96875000e-01,  1.00000000e+00]],

   [[-1.37695313e-02,  2.60742188e-02, -4.68750000e-02],
    [-6.60937500e-02,  1.25156250e-01, -2.25000000e-01],
    [ 2.93750000e-01, -5.56250000e-01,  1.00000000e+00]],

   [[-2.77148437e-02,  1.25039062e-01, -2.06250000e-01],
    [-1.63769531e-02,  7.38867187e-02, -1.21875000e-01],
    [ 1.34375000e-01, -6.06250000e-01,  1.00000000e+00]],

   [[ 1.98632813e-02,  2.42773438e-01, -3.53125000e-01],
    [ 2.46093750e-03,  3.00781250e-02, -4.37500000e-02],
    [-5.62500000e-02, -6.87500000e-01,  1.00000000e+00]],

   [[ 7.27539062e-02, -5.76171875e-02,  1.56250000e-01],
    [-9.31250000e-02,  7.37500000e-02, -2.00000000e-01],
    [ 4.65625000e-01, -3.68750000e-01,  1.00000000e+00]],

   [[-1.21875000e-02,  1.57031250e-02, -3.75000000e-02],
    [-3.25000000e-02,  4.18750000e-02, -1.00000000e-01],
    [ 3.25000000e-01,

In [14]:
from umucv.tensor import nullTensor

F = nullTensor(D,'ji')

F

 [28] [3 3] (28, 9) 9 


T([[ 0.03389614,  0.17832885, -0.25265227],
   [ 0.15881605,  0.08356661, -0.58058121],
   [-0.2051127 ,  0.64632575,  0.27226467]],'ij')

In [15]:
D @ F

T([-4.36888426e-04, -8.86855987e-04,  6.67711016e-04,  9.42722057e-04,
   -1.36967090e-03,  3.21175112e-03, -7.29968251e-04, -2.66729279e-03,
    1.05309555e-03, -1.40489810e-04, -3.12881420e-03,  4.70629769e-03,
   -2.08495303e-03,  2.67220711e-03, -1.78313610e-03,  5.47466046e-04,
    1.07785934e-03,  1.44822223e-05, -1.43377528e-03, -3.79639562e-03,
    1.92647423e-03,  4.57827863e-03, -2.87820782e-04,  5.13116845e-04,
   -3.13039574e-03, -2.88720220e-03,  1.48921717e-03,  1.39977555e-03],'n')

In [16]:
D @ F.reorder('ji')

T([-4.36888426e-04, -8.86855987e-04,  6.67711016e-04,  9.42722057e-04,
   -1.36967090e-03,  3.21175112e-03, -7.29968251e-04, -2.66729279e-03,
    1.05309555e-03, -1.40489810e-04, -3.12881420e-03,  4.70629769e-03,
   -2.08495303e-03,  2.67220711e-03, -1.78313610e-03,  5.47466046e-04,
    1.07785934e-03,  1.44822223e-05, -1.43377528e-03, -3.79639562e-03,
    1.92647423e-03,  4.57827863e-03, -2.87820782e-04,  5.13116845e-04,
   -3.13039574e-03, -2.88720220e-03,  1.48921717e-03,  1.39977555e-03],'n')

In [17]:
D @ F('ji')

T([0.19891031, 0.38753445, 0.57599818, 0.7719616 , 0.19027047,
   0.37611467, 0.57814716, 0.75271665, 0.19285201, 0.37722304,
   0.57537676, 0.74352056, 0.22180882, 0.39623049, 0.58823805,
   0.7548587 , 0.27251214, 0.42885774, 0.57874711, 0.72141311,
   0.32142541, 0.44327345, 0.58200954, 0.69680351, 0.35418122,
   0.46599852, 0.57893959, 0.67448378],'n')

## Homography estimation

In [18]:
x = v1
h = np.array([[1,2,3],
              [4,5,6],
              [1,1,1]])
y = T(homog(inhomog(v1.A @ h.T)), 'nj')

In [19]:
y

T([[3.07335907, 6.07335907, 1.        ],
   [3.43776824, 6.43776824, 1.        ],
   [3.79534884, 6.79534884, 1.        ],
   [4.24352332, 7.24352332, 1.        ],
   [2.88235294, 5.88235294, 1.        ],
   [3.20289855, 6.20289855, 1.        ],
   [3.53754941, 6.53754941, 1.        ],
   [3.83898305, 6.83898305, 1.        ],
   [2.70844687, 5.70844687, 1.        ],
   [2.95857988, 5.95857988, 1.        ],
   [3.27540984, 6.27540984, 1.        ],
   [3.58992806, 6.58992806, 1.        ],
   [2.5458613 , 5.5458613 , 1.        ],
   [2.78271605, 5.78271605, 1.        ],
   [3.06849315, 6.06849315, 1.        ],
   [3.33035714, 6.33035714, 1.        ],
   [2.38563327, 5.38563327, 1.        ],
   [2.56326531, 5.56326531, 1.        ],
   [2.75055188, 5.75055188, 1.        ],
   [2.93824228, 5.93824228, 1.        ],
   [2.28618968, 5.28618968, 1.        ],
   [2.42576029, 5.42576029, 1.        ],
   [2.57743786, 5.57743786, 1.        ],
   [2.73045267, 5.73045267, 1.        ],
   [2.22358346, 

In [20]:
from umucv.tensor import eps3

In [21]:
D = x * y

H = nullTensor(D @ eps3('ikl'), 'kj')

H

 [ 3 28] [3 3] (84, 9) 6 


T([[ 0.01439106,  0.05603656, -0.29590859],
   [-0.01439106, -0.05603656,  0.29590859],
   [ 0.04317319,  0.16810968, -0.88772576]],'jk')

In [22]:
H.A / H.A[2,2]

array([[-0.01621116, -0.06312373,  0.33333333],
       [ 0.01621116,  0.06312373, -0.33333333],
       [-0.04863348, -0.18937118,  1.        ]])

In [23]:
H = nullTensor(D @ eps3('jkl'), 'ki')

H

 [ 3 28] [3 3] (84, 9) 8 


T([[0.10314212, 0.4125685 , 0.10314212],
   [0.20628425, 0.51571062, 0.10314212],
   [0.30942637, 0.61885275, 0.10314212]],'ik')

In [24]:
H.A / H.A[2,2]

array([[1., 4., 1.],
       [2., 5., 1.],
       [3., 6., 1.]])

## Triangulation

Interesting example of diagonal extraction, or zipping of structures.

In [25]:
cam1 = np.array([[ 512.,    0.,  320.,    0.],
       [   0.,  512.,  240.,    0.],
       [   0.,    0.,    1.,    0.]])

cam2 = np.array([[  27.505, -275.084,  536.765, -352.55 ],
 [  83.161,  429.114,  358.733,    4.747],
 [  -0.711,    0.118,    0.693,    0.365]])

In [26]:
C = T(np.array([cam1,cam2]),'cvw')

with np.printoptions(precision=2, suppress=True, threshold=5):
    print(C)

cvw
[[[ 512.      0.    320.      0.  ]
  [   0.    512.    240.      0.  ]
  [   0.      0.      1.      0.  ]]

 [[  27.5  -275.08  536.76 -352.55]
  [  83.16  429.11  358.73    4.75]
  [  -0.71    0.12    0.69    0.36]]]


In [27]:
p3d = np.array([[-0.11067118,  0.23208958,  1.22959005],
       [ 0.02605047,  0.15929016,  1.24963072],
       [ 0.15278893,  0.07876401,  1.27626139],
       [ 0.28030864,  0.01599885,  1.32861132],
       [-0.11708948,  0.12661194,  1.11779301],
       [ 0.01689746,  0.05494264,  1.14177591],
       [ 0.14953718, -0.02034495,  1.17971911],
       [ 0.26161823, -0.08734784,  1.21791671],
       [-0.12340494,  0.01364562,  0.99764912],
       [ 0.00155168, -0.05596433,  1.02972522],
       [ 0.1373791 , -0.12411526,  1.06717139],
       [ 0.2536887 , -0.18816734,  1.10157925],
       [-0.1350337 , -0.09502867,  0.88719839],
       [-0.01000757, -0.15792879,  0.92912773],
       [ 0.12754962, -0.22443005,  0.9629846 ],
       [ 0.24391027, -0.29002987,  1.003195  ],
       [-0.2249506 , -0.18288471,  0.98481174],
       [-0.08823046, -0.25155878,  1.00771513],
       [ 0.03940784, -0.31658844,  1.04822339],
       [ 0.15922148, -0.37992148,  1.09645965],
       [-0.31134116, -0.28020144,  1.07610716],
       [-0.1769637 , -0.33922077,  1.09961827],
       [-0.03994644, -0.41138884,  1.13923163],
       [ 0.08090013, -0.46762971,  1.18893698],
       [-0.39645445, -0.35924587,  1.17213933],
       [-0.25438077, -0.41932229,  1.19260766],
       [-0.11169695, -0.48399993,  1.22616359],
       [-0.00422111, -0.5485228 ,  1.28709172]])

In [28]:
#views = C @ T(homog(p3d[[0,1],:]),'nw')
#views

In [29]:
views = C @ T(homog(p3d[0]),'w')
views = T(homog(np.random.rand(2,2)+inhomog(views.A)),'cv')

In [30]:
views

T([[273.92989893, 337.53856129,   1.        ],
   [182.70483509, 405.45428912,   1.        ]],'cv')

In [31]:
p3d[0]

array([-0.11067118,  0.23208958,  1.22959005])

In [32]:
X =  T(homog(p3d[0]),'w')

In [33]:
C @ X

T([[336.80517184, 413.93147696,   1.22959005],
   [240.56276236, 536.23088944,   1.32317968]],'cv')

In [34]:
C @ X @ eps3('vij')

T([[[   0.        ,    1.22959005, -413.93147696],
    [  -1.22959005,    0.        ,  336.80517184],
    [ 413.93147696, -336.80517184,    0.        ]],

   [[   0.        ,    1.32317968, -536.23088944],
    [  -1.32317968,    0.        ,  240.56276236],
    [ 536.23088944, -240.56276236,    0.        ]]],'cij')

In [35]:
C @ X @ eps3('vij')  @ views('qi')

T([[[-1.10257950e+00, -8.46110827e+01],
    [ 1.63062861e-02, -1.12153125e+02],
    [ 2.96525490e+02,  6.09318193e+04]],

   [[ 8.96067225e+01, -2.57988745e-01],
    [ 1.21895715e+02,  1.18856361e+00],
    [-6.56904646e+04, -4.34772423e+02]]],'cjq')

In [36]:
mul(C @ X @ eps3('vij')  , views('ci'), sum='i')

T([[-1.10257950e+00,  1.63062861e-02,  2.96525490e+02],
   [-2.57988745e-01,  1.18856361e+00, -4.34772423e+02]],'cj')

In [37]:
mul(C @ eps3('vij')  , views('ci'), 'i')

T([[[ 0.00000000e+00,  5.12000000e+02, -9.75385613e+01,
      0.00000000e+00],
    [-5.12000000e+02,  0.00000000e+00, -4.60701011e+01,
      0.00000000e+00],
    [ 1.72819743e+05, -1.40252108e+05,  4.22691639e+04,
      0.00000000e+00]],

   [[ 3.71439000e+02,  3.81270394e+02,  7.77531776e+01,
     -1.43243816e+02],
    [-1.57408138e+02,  2.96643171e+02, -4.10150549e+02,
      4.19237265e+02],
    [-4.04189657e+03, -1.89935190e+05,  1.52091418e+05,
     -1.43810209e+05]]],'cjw')

In [38]:
nullTensor( mul(C @ eps3('vij')  , views('ci'), 'i'), 'w')

 [2 3] [4] (6, 4) 4 


T([ 0.06957238, -0.14543335, -0.76700866, -0.62105277],'w')

In [39]:
inhomog(_.A)

array([-0.1120233 ,  0.23417229,  1.23501367])

In [40]:
p3d[0]

array([-0.11067118,  0.23208958,  1.22959005])

In [41]:
nullTensor(C @ eps3('vij')  @ views('ci'), 'w')

 [3] [4] (3, 4) 3 


T([-0.0676642 ,  0.14496995,  0.76585353,  0.62279503],'w')

In [42]:
inhomog(_.A)

array([-0.10864601,  0.23277313,  1.22970398])

In [43]:
C

T([[[ 5.12000e+02,  0.00000e+00,  3.20000e+02,  0.00000e+00],
    [ 0.00000e+00,  5.12000e+02,  2.40000e+02,  0.00000e+00],
    [ 0.00000e+00,  0.00000e+00,  1.00000e+00,  0.00000e+00]],

   [[ 2.75050e+01, -2.75084e+02,  5.36765e+02, -3.52550e+02],
    [ 8.31610e+01,  4.29114e+02,  3.58733e+02,  4.74700e+00],
    [-7.11000e-01,  1.18000e-01,  6.93000e-01,  3.65000e-01]]],'cvw')

In [44]:
mapAt(lambda c: c @ X, C ,'c')

T([[336.80517184, 413.93147696,   1.22959005],
   [240.56276236, 536.23088944,   1.32317968]],'cv')

In [45]:
C @ X

T([[336.80517184, 413.93147696,   1.22959005],
   [240.56276236, 536.23088944,   1.32317968]],'cv')

## Exterior product and dual

In [46]:
(T([1,0,0]) ^ T([0,1,0])) @ eps3

T([0., 0., 2.],'k')

In [47]:
from umucv.tensor import eps4

In [48]:
eps4

T([[[[ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.]],

    [[ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  1.],
     [ 0.,  0., -1.,  0.]],

    [[ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0., -1.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  1.,  0.,  0.]],

    [[ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  1.,  0.],
     [ 0., -1.,  0.,  0.],
     [ 0.,  0.,  0.,  0.]]],


   [[[ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0., -1.],
     [ 0.,  0.,  1.,  0.]],

    [[ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.]],

    [[ 0.,  0.,  0.,  1.],
     [ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.],
     [-1.,  0.,  0.,  0.]],

    [[ 0.,  0., -1.,  0.],
     [ 0.,  0.,  0.,  0.],
     [ 1.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  0.]]],


   [[[ 0.,  0.,  0.,  0.],
     [ 0.,  0.,  0.,  1.],
     [ 0.,  0.,  0.,  0.],
     [ 0., -1.,  0.,  0.]],

    [[

In [49]:
p = T([1,0,0,1])
q = T([0,1,0,1])
l = p ^ q

In [50]:
l

T([[ 0,  1,  0,  1],
   [-1,  0,  0, -1],
   [ 0,  0,  0,  0],
   [-1,  1,  0,  0]],'ij')

In [51]:
l @ eps4

T([[ 0.,  0.,  2.,  0.],
   [ 0.,  0.,  2.,  0.],
   [-2., -2.,  0.,  2.],
   [ 0.,  0., -2.,  0.]],'kl')

In [52]:
(l @ eps4) @ eps4

T([[ 0.,  4.,  0.,  4.],
   [-4.,  0.,  0., -4.],
   [ 0.,  0.,  0.,  0.],
   [-4.,  4.,  0.,  0.]],'ij')

In [53]:
eps4 @ eps4

T(24.,'')

In [54]:
eps4 @ eps4('jklb')

T([[-6.,  0.,  0.,  0.],
   [ 0., -6.,  0.,  0.],
   [ 0.,  0., -6.,  0.],
   [ 0.,  0.,  0., -6.]],'bi')